version: '3.3'

services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DB_NAME}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - armaservermanager-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: db
      PMA_USER: "${MYSQL_USER}"
      PMA_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3000:80"
    volumes:
      - ./phpmyadmin/sessions:/sessions
     
  armaservermanager:
    #image: "fugasjunior/armaservermanager:${VERSION}"
    build:
      context: .
      dockerfile: Dockerfile

    restart: always
    # 'host' network mode is not available on Windows. If you need to run this image on Windows, you need to set up port mappings manually.
    #network_mode: host
    # uncomment when running on Windows and add additional ports according to your needs
    ports:
      - "8080:8080"
      - "2302-2305:2302-2305/udp"
      - "27016:27016/udp"
    depends_on:
      - db
    volumes:
      - "${STORAGE_PATH}:/home/steam/armaservermanager/"
    environment:
      AUTH_USERNAME: "${AUTH_USERNAME}"
      AUTH_PASSWORD: "${AUTH_PASSWORD}"
      SPRING_DATASOURCE_URL: "${MYSQL_DB_URL}"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
      STEAM_API_KEY: "${STEAM_API_KEY}"
      JWT_SECRET: "${JWT_SECRET}"
      DATABASE_ENCRYPTION_SECRET: "${DATABASE_ENCRYPTION_SECRET}"
      TZ: "${TIMEZONE}"

volumes:
  armaservermanager-db:
