version: '3.8'

services:
  armaservermanager:
    #image: "fugasjunior/armaservermanager:${VERSION}"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
      - "2302-2305:2302-2305/udp"
      - "27016:27016/udp"
    depends_on:
      - db
    volumes:
      - "${STORAGE_PATH}:/home/steam/armaservermanager/"
    environment:
      AUTH_USERNAME: "${AUTH_USERNAME}"
      AUTH_PASSWORD: "${AUTH_PASSWORD}"
      SPRING_DATASOURCE_URL: "${MYSQL_DB_URL}"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
      STEAM_API_KEY: "${STEAM_API_KEY}"
      JWT_SECRET: "${JWT_SECRET}"
      DATABASE_ENCRYPTION_SECRET: "${DATABASE_ENCRYPTION_SECRET}"
      TZ: "${TIMEZONE}"
    cpuset: "0,1,2,3"

  teamspeak:
    image: teamspeak:3.13
    restart: always
    ports:
      - "9987:9987/udp"
      - "10011:10011"
      - "30033:30033"
    volumes:
      - ./teamspeak:/var/ts3server
    environment:
      TS3SERVER_LICENSE: accept
    cpuset: "4,5"

  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DB_NAME}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - armaservermanager-db:/var/lib/mysql
    cpuset: "6,7"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: db
      PMA_USER: "${MYSQL_USER}"
      PMA_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3000:80"
    volumes:
      - ./phpmyadmin/sessions:/sessions
    cpuset: "6,7"
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    cpuset: "6,7"

volumes:
  armaservermanager-db:
